version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:864899837235:task-definition/user30_task_def:1"
        LoadBalancerInfo:
          ContainerName: "user30_container_1"
          ContainerPort: 80
